## Importando datos mediante una ruta correspondiente y Guardando

In [2]:
## En esta seccion se realizara una importacion de un dataset correspondiente pero se encuentra en una ruta

## Importacion de librerias
import pandas as pd
from tabulate import tabulate

df = pd.read_csv(r"C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada\Concursos.csv",delimiter=';')

# Ahora puedes trabajar con los datos utilizando Pandas
# Por ejemplo, puedes imprimir las primeras filas del DataFrame
df

,COD. TIENDA,CADENA,LOCAL,INDICADOR,SEMANA,DETALLE,aw,PUNTOS,Categoria,MARCA
0,313,TOTTUS,Tottus Ica,EEAA,Semana 1,Minicabecera,1,80,ANGEL,Angel Clasico
1,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Lateral,1,90,ANGEL,Casino Break
2,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Lateral,6,540,ANGEL,Angel Clasico
3,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Minicabecera,1,80,ANGEL,Casino Break
4,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Punto de Caja,2,140,ANGEL,Casino Break
...,...,...,...,...,...,...,...,...,...,...
57,S081,METRO,Metro El Ejercito,EEAA,Semana 4,Minicabecera,1,80,ANGEL,Angel Almohadas
58,S085,METRO,Metro Grau,EEAA,Semana 4,Cabecera,1,100,ANGEL,Angel Clasico
59,S037,METRO,Metro Balta,EEAA,Semana 4,Cabecera,1,100,ANGEL,Angel Clasico
60,S014,METRO,Metro Ventanilla,EEAA,Semana 4,Ruma,1,100,ANGEL,Angel Clasico
61,H013,METRO,Metro Fiori - Independencia,EEAA,Semana 4,Chimenea,1,80,ANGEL,Angel Almohadas

In [4]:
filtro = df.loc[df['CADENA']=='TOTTUS'].head(5)
filtro

,COD. TIENDA,CADENA,LOCAL,INDICADOR,SEMANA,DETALLE,aw,PUNTOS,Categoria,MARCA
0,313,TOTTUS,Tottus Ica,EEAA,Semana 1,Minicabecera,1,80,ANGEL,Angel Clasico
1,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Lateral,1,90,ANGEL,Casino Break
2,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Lateral,6,540,ANGEL,Angel Clasico
3,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Minicabecera,1,80,ANGEL,Casino Break
4,332,TOTTUS,Tottus Chincha,EEAA,Semana 1,Punto de Caja,2,140,ANGEL,Casino Break

In [8]:
## Guardar archivo en una ruta especifica

df.to_csv(r"C:\Users\User\OneDrive\Documentos\Archivos_Carlos\Test_Output_python_rout.csv", index=False)

In [ ]:
import pandas as pd

ruta_archivo_lectura = r"C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada\Concursos.csv"
ruta_archivo_escritura = r"C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada\Test_Output_python_rout.csv"

# Leer el archivo CSV en un DataFrame
df = pd.read_csv(ruta_archivo_lectura)

# Realizar operaciones o modificaciones en el DataFrame si es necesario

# Guardar el DataFrame en la nueva ubicaciÃ³n
df.to_csv(ruta_archivo_escritura, index=False)