## Identificacion de Duplicados , Eliminacion -> Pre ETL

In [1]:
import pandas as pd
from tabulate import tabulate

df = pd.read_excel(r"C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada\Identificar Duplicaods.xlsx")
df.head(5)

,Fechas,Codigo_Producto,Categoria_Producto,Nombre_Producto,Marca_Producto
0,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
1,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
2,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
3,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
4,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria

In [14]:
## Cantidad de registros totales
print(f'La cantidad del dataset es de {df.shape[0]} registros') ## El siguiente parametro realiza la cuenta considerando la primera columna en este caso seria fechas

La cantidad del dataset es de 625434 registros

In [19]:
##  Ejercicio 1 : 
    ## Se solicita obtener la data final sin duplicados. Considerar que en total deberia se deberia obtener 70638 Registros Mostrarlo en formato datafram y tabulado.
    ## Asi mismo, se pide que se cree el output final donde el nombre del archivo sera Data_No_Duplicada el archivo de salida debe ser Plano (csv)
    ## Realizarlo de las 2 formas posibles
    
## Forma 1

ejercicio_1 = df.drop_duplicates(subset=df.columns) ## En este algoritmo se esta considerando todos las columnas de manera mas automatica
ejercicio_1

,Fechas,Codigo_Producto,Categoria_Producto,Nombre_Producto,Marca_Producto
0,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
6,2022-01-04,4527205,Galletas,Gall.Vict. Tentacion Coco 45 grs 6Pqt8Pck - 45...,Victoria
21,2022-01-04,4527206,Galletas,Gall.Vict.Tentacion Vainilla 45 grs 6Pqt8Pck -...,Victoria
34,2022-01-04,4527207,Galletas,Gall.Vict.Tentacion Naranja 45 grs 6Pqt8Pck - ...,Victoria
50,2022-01-04,5003029,Cereales,Cereales Tito Almohada 110 grs x 30 Bol - 5003029,Angel
...,...,...,...,...,...
625365,2022-06-24,6701004,Pre Mezclas,Mezcla Blanca Flor Tc Choco 0.8 kg 24Bol - 670...,Blanca Flor
625379,2022-06-24,6701022,Harinas,Harina Blanca Flor Sin Prep.1 kg 12Bol - 6701022,Blanca Flor
625392,2022-06-24,6702008,Harinas,Harina Favorita Sin Preparar 1 kg 12Bol - 6702008,Favorita
625424,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625433,2022-07-31,9550021,Lavavajillas,Lavavajillas Marsella 900 ml .9Fco - 9550021,Marsella

In [22]:
## Forma 2

eje1_f2 = df.drop_duplicates(subset=['Fechas','Codigo_Producto','Categoria_Producto','Nombre_Producto','Marca_Producto'])
eje1_f2

,Fechas,Codigo_Producto,Categoria_Producto,Nombre_Producto,Marca_Producto
0,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
6,2022-01-04,4527205,Galletas,Gall.Vict. Tentacion Coco 45 grs 6Pqt8Pck - 45...,Victoria
21,2022-01-04,4527206,Galletas,Gall.Vict.Tentacion Vainilla 45 grs 6Pqt8Pck -...,Victoria
34,2022-01-04,4527207,Galletas,Gall.Vict.Tentacion Naranja 45 grs 6Pqt8Pck - ...,Victoria
50,2022-01-04,5003029,Cereales,Cereales Tito Almohada 110 grs x 30 Bol - 5003029,Angel
...,...,...,...,...,...
625365,2022-06-24,6701004,Pre Mezclas,Mezcla Blanca Flor Tc Choco 0.8 kg 24Bol - 670...,Blanca Flor
625379,2022-06-24,6701022,Harinas,Harina Blanca Flor Sin Prep.1 kg 12Bol - 6701022,Blanca Flor
625392,2022-06-24,6702008,Harinas,Harina Favorita Sin Preparar 1 kg 12Bol - 6702008,Favorita
625424,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625433,2022-07-31,9550021,Lavavajillas,Lavavajillas Marsella 900 ml .9Fco - 9550021,Marsella

In [55]:
## Exportando el archivo ouput sin duplicidades de manera profesional como ingeniero de software
## Creando las variables para la salida correspondiente

despositorio_ruta = r'C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada'
nombre_archivo = 'Data_No_Duplicada.csv'

for i in range (1,2):
    try:
        if i == 1:
            eje1_f2.to_csv(r'C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada\Data_No_Duplicada.csv',index=False)  ## Index = false para evitar los indices de cada registro
            print(f'El archivo {nombre_archivo} se guardo exitosamente en la ruta {despositorio_ruta}')
    except Exception as e:
        print(f'Existe error al guardar el archivo,favor de revisar.')

El archivo Data_No_Duplicada.csv se guardo exitosamente en la ruta C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada

In [65]:
## Ejercicio 2 :
    ## Se solicita obtener unicamente los registros que se estan duplicando y colocarlo en un archivo csv en la ruta de BBDD - No Estructurada

Ejercicio_2 = df[df.duplicated(keep='last')]
Ejercicio_2 ## Resultado

,Fechas,Codigo_Producto,Categoria_Producto,Nombre_Producto,Marca_Producto
0,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
1,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
2,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
3,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
4,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
...,...,...,...,...,...
625427,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625428,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625429,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625430,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625431,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar

In [74]:
## Subscribiendo los mismo datos al mismo data set 
consolidado = pd.concat([ejercicio_1,Ejercicio_2])
consolidado

,Fechas,Codigo_Producto,Categoria_Producto,Nombre_Producto,Marca_Producto
0,2022-01-04,4527204,Galletas,Gall. Vict. Tentacion Choco 45 grs. 6Pqt 8Pck ...,Victoria
6,2022-01-04,4527205,Galletas,Gall.Vict. Tentacion Coco 45 grs 6Pqt8Pck - 45...,Victoria
21,2022-01-04,4527206,Galletas,Gall.Vict.Tentacion Vainilla 45 grs 6Pqt8Pck -...,Victoria
34,2022-01-04,4527207,Galletas,Gall.Vict.Tentacion Naranja 45 grs 6Pqt8Pck - ...,Victoria
50,2022-01-04,5003029,Cereales,Cereales Tito Almohada 110 grs x 30 Bol - 5003029,Angel
...,...,...,...,...,...
625427,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625428,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625429,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625430,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar
625431,2022-07-31,9350393,Suavizantes,Suav Bol Plus Lavanda 1.5 lts 8Dpk - 9350393,Bolivar

In [63]:
## Exportando los datos duplicados aislados a la ruta correspondiente :

ruta = r'C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada'
output = 'Data_Duplicada_Aislada.csv'

for i in range (1,2):
    try:
        if i ==1:
            Ejercicio_2.to_csv(r'C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada\Data_Duplicada_Aislada.csv',index=False)
            print(f'El archivo {output} se guardo de manera exitosa en la ruta {ruta}')
    except Exception as e:
        print('Surgio un problema en el guardado del nuevo dataset, favor de revisar el codigo correspondientemente')

El archivo Data_Duplicada_Aislada.csv se guardo de manera exitosa en la ruta C:\Users\User\OneDrive\Documentos\Archivos_Carlos\BBDD - No estructurada